/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import common.Utility;
import dao.ProductsDao;
import entity.Products;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import org.hibernate.Session;

/**
 *
 * @author tien.lvt
 */
public class UpdateProduct extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1781270044444263719L;
	private final JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
	private Products oldClazz = new Products();
	private static int id;
	private ProductsDao dao;

	/**
	 * Creates new form UpdateProduct
	 */
	public UpdateProduct() throws Exception {
		initComponents();
		Session session = null;
		try {
			session = dao.getSession();
			this.oldClazz = session.find(Products.class, id);
		} catch (Exception ex) {

		} finally {
			Utility.closeObject(session);
		}
		if (this.oldClazz != null) {
			this.name.setText(oldClazz.getName());
			this.kind.setText(oldClazz.getKind());
			this.salePrice.setText(String.valueOf(oldClazz.getPriceOut()));
			this.quantity.setText(String.valueOf(oldClazz.getQuantities()));
			this.ExpDate.setText(Utility.dateToString(oldClazz.getExpDate()));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		salePrice = new javax.swing.JTextField();
		kind = new javax.swing.JTextField();
		quantity = new javax.swing.JTextField();
		button1 = new java.awt.Button();
		jLabel6 = new javax.swing.JLabel();
		ExpDate = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		setPreferredSize(new java.awt.Dimension(802, 596));

		jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		jLabel1.setText("Name");

		jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		jLabel2.setText("Sale Price");

		jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		jLabel3.setText("Kind");

		jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		jLabel4.setText("Quantity");

		jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		jLabel5.setText("Url Image");

		name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

		salePrice.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

		kind.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

		quantity.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		quantity.setFocusTraversalPolicyProvider(true);

		button1.setActionCommand("Choice Image");
		button1.setLabel("Choice Image");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
		jLabel6.setText("Exp Date");

		ExpDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

		jButton1.setText("Fix");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(144, 144, 144)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2).addComponent(jLabel3).addComponent(jLabel4)
										.addComponent(jLabel5).addComponent(jLabel1).addComponent(jLabel6))
								.addGap(75, 75, 75)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(quantity, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
										.addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(kind, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(salePrice, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(button1, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
										.addComponent(ExpDate))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(368, Short.MAX_VALUE)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(265, 265, 265)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(152, 152, 152)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addGap(15, 15, 15)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2).addComponent(salePrice, javax.swing.GroupLayout.PREFERRED_SIZE,
										35, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(kind, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel5).addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(ExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(54, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_button1ActionPerformed
		// System.out.println("form.InsertProduct.button1ActionPerformed()"+
		// jfc.getAcceptAllFileFilter().toString());
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("JPG image", "JPG"));
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("PNG image", "PNG"));
		jfc.showOpenDialog(null);
		// int returnValue = jfc.showSaveDialog(null);
		/*
		 * if (returnValue == JFileChooser.APPROVE_OPTION) { File selectedFile =
		 * jfc.getSelectedFile(); System.out.println(selectedFile.getAbsolutePath());
		 * System.out.println(selectedFile.getPath()); }
		 */
	}// GEN-LAST:event_button1ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		oldClazz.setName(this.name.getText());
		oldClazz.setKind(this.kind.getText());
		oldClazz.setPriceOut(Utility.convertDouble(this.salePrice.getText()));
		oldClazz.setQuantities(Utility.convertInt(this.quantity.getText()));
		oldClazz.setStatus("O");
		try {
			oldClazz.setExpDate(Utility.fomatDate(this.ExpDate.getText()));
			Utility.copyFileUsingStream(jfc.getSelectedFile(), new File(oldClazz.getUrl()));
			HomeProduct.dao.updateOne(oldClazz, id);
		} catch (Exception ex) {

		}
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField ExpDate;
	private java.awt.Button button1;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField kind;
	private javax.swing.JTextField name;
	private javax.swing.JTextField quantity;
	private javax.swing.JTextField salePrice;
	// End of variables declaration//GEN-END:variables
}
