package entity;
// Generated Dec 5, 2019 7:51:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Bills generated by hbm2java
 */
public class Bills implements java.io.Serializable {

	private Integer id;
	private Members members;
	private int quantities;
	private String addresss;
	private Date receiveDate;
	private double disCount;
	private int proId;

	public Bills() {
	}

	public Bills(Members members, int quantities, String addresss, Date receiveDate, double disCount, int proId) {
		this.members = members;
		this.quantities = quantities;
		this.addresss = addresss;
		this.receiveDate = receiveDate;
		this.disCount = disCount;
		this.proId = proId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Members getMembers() {
		return this.members;
	}

	public void setMembers(Members members) {
		this.members = members;
	}

	public int getQuantities() {
		return this.quantities;
	}

	public void setQuantities(int quantities) {
		this.quantities = quantities;
	}

	public String getAddresss() {
		return this.addresss;
	}

	public void setAddresss(String addresss) {
		this.addresss = addresss;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public double getDisCount() {
		return this.disCount;
	}

	public void setDisCount(double disCount) {
		this.disCount = disCount;
	}

	public int getProId() {
		return this.proId;
	}

	public void setProId(int proId) {
		this.proId = proId;
	}

}
