package entity;
// Generated Dec 5, 2019 8:22:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "javaproject2")
public class Products implements java.io.Serializable {

	private Integer id;
	private String name;
	private double priceIn;
	private double priceOut;
	private String kind;
	private int quantities;
	private Date importDate;
	private Date expDate;
	private String url;
	private Set<Bills> billses = new HashSet<Bills>(0);

	public Products() {
	}

	public Products(String name, double priceIn, double priceOut, String kind, int quantities, Date importDate,
			Date expDate, String url) {
		this.name = name;
		this.priceIn = priceIn;
		this.priceOut = priceOut;
		this.kind = kind;
		this.quantities = quantities;
		this.importDate = importDate;
		this.expDate = expDate;
		this.url = url;
	}

	public Products(String name, double priceIn, double priceOut, String kind, int quantities, Date importDate,
			Date expDate, String url, Set<Bills> billses) {
		this.name = name;
		this.priceIn = priceIn;
		this.priceOut = priceOut;
		this.kind = kind;
		this.quantities = quantities;
		this.importDate = importDate;
		this.expDate = expDate;
		this.url = url;
		this.billses = billses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PriceIn", nullable = false, precision = 22, scale = 0)
	public double getPriceIn() {
		return this.priceIn;
	}

	public void setPriceIn(double priceIn) {
		this.priceIn = priceIn;
	}

	@Column(name = "PriceOut", nullable = false, precision = 22, scale = 0)
	public double getPriceOut() {
		return this.priceOut;
	}

	public void setPriceOut(double priceOut) {
		this.priceOut = priceOut;
	}

	@Column(name = "Kind", nullable = false, length = 50)
	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	@Column(name = "Quantities", nullable = false)
	public int getQuantities() {
		return this.quantities;
	}

	public void setQuantities(int quantities) {
		this.quantities = quantities;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ImportDate", nullable = false, length = 10)
	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ExpDate", nullable = false, length = 10)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "Url", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Bills> getBillses() {
		return this.billses;
	}

	public void setBillses(Set<Bills> billses) {
		this.billses = billses;
	}

}
