package entity;
// Generated Dec 5, 2019 7:51:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private Integer id;
	private String name;
	private double priceIn;
	private double priceOut;
	private String kind;
	private int quantities;
	private Date importDate;
	private Date expDate;
	private String url;

	public Products() {
	}

	public Products(String name, double priceIn, double priceOut, String kind, int quantities, Date importDate,
			Date expDate, String url) {
		this.name = name;
		this.priceIn = priceIn;
		this.priceOut = priceOut;
		this.kind = kind;
		this.quantities = quantities;
		this.importDate = importDate;
		this.expDate = expDate;
		this.url = url;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPriceIn() {
		return this.priceIn;
	}

	public void setPriceIn(double priceIn) {
		this.priceIn = priceIn;
	}

	public double getPriceOut() {
		return this.priceOut;
	}

	public void setPriceOut(double priceOut) {
		this.priceOut = priceOut;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public int getQuantities() {
		return this.quantities;
	}

	public void setQuantities(int quantities) {
		this.quantities = quantities;
	}

	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
