package entity;
// Generated Dec 5, 2019 7:51:04 PM by Hibernate Tools 4.3.5.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String name;
	private String pwd;
	private int role;

	public Users() {
	}

	public Users(String name, String pwd, int role) {
		this.name = name;
		this.pwd = pwd;
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

}
